# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      main_src_minor_updates:
        update-types:
          - "minor"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-patch" ]
  - package-ecosystem: "nuget"
    directory: "/test"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    groups:
      test_minor_updates:
        update-types:
          - "minor"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-patch" ]
